import chartobase64

print('Man')
print(chartobase64.chartobase64('Man'))
print('\n')
print('h a b')
print(chartobase64.chartobase64('h a b'))
print('\n')
print('pleasure.')
print(chartobase64.chartobase64('pleasure.'))
print('\n')
print('leasure.')
print(chartobase64.chartobase64('leasure.'))
print('\n')
print('easure.')
print(chartobase64.chartobase64('easure.'))
print('\n')
print('asure.')
print(chartobase64.chartobase64('asure.'))
print('\n')
print('sure.')
print(chartobase64.chartobase64('sure.'))
print('\n')
